/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "oauth.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

AuthResponse *
auth_1(AuthRequest arg1,  CLIENT *clnt)
{
	static AuthResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, auth,
		(xdrproc_t) xdr_AuthRequest, (caddr_t) &arg1,
		(xdrproc_t) xdr_AuthResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ApproveTokenResponse *
approve_token_1(ApproveTokenRequest arg1,  CLIENT *clnt)
{
	static ApproveTokenResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, approve_token,
		(xdrproc_t) xdr_ApproveTokenRequest, (caddr_t) &arg1,
		(xdrproc_t) xdr_ApproveTokenResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

OauthAccessTokenResponse *
oauth_access_token_1(OauthAccessTokenRequest arg1,  CLIENT *clnt)
{
	static OauthAccessTokenResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, oauth_access_token,
		(xdrproc_t) xdr_OauthAccessTokenRequest, (caddr_t) &arg1,
		(xdrproc_t) xdr_OauthAccessTokenResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

OauthAccessTokenResponse *
oauth_refresh_token_1(OauthRefreshTokenRequest arg1,  CLIENT *clnt)
{
	static OauthAccessTokenResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, oauth_refresh_token,
		(xdrproc_t) xdr_OauthRefreshTokenRequest, (caddr_t) &arg1,
		(xdrproc_t) xdr_OauthAccessTokenResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ExecuteActionResponse *
execute_action_1(ExecuteActionRequest arg1,  CLIENT *clnt)
{
	static ExecuteActionResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, execute_action,
		(xdrproc_t) xdr_ExecuteActionRequest, (caddr_t) &arg1,
		(xdrproc_t) xdr_ExecuteActionResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
